import { Component, signal } from '@angular/core';
import packageJson from '../../../../package.json';

@Component({
  selector: 'app-used-colors',
  imports: [],
  templateUrl: './used-assets.component.html',
  styleUrl: './used-assets.component.css',
})
export class UsedAssets {

  dependencies = signal<string[]>([]);

  constructor() {
    const deps = Object.entries(packageJson.dependencies || {});
    const devDeps = Object.entries(packageJson.devDependencies || {});

    const allDeps = [...deps, ...devDeps].map(([name, ver]) => `${name} @ ${ver}`);

    this.dependencies.set(allDeps);
  }

  imgUrls: string[] = [
    'https://www.dexerto.com/destiny/destiny-2-players-find-broken-deep-engram-farm-that-drops-one-every-minute-2156304/',
    'https://steamcommunity.com/sharedfiles/filedetails/?id=1879473494',
    'https://destiny.fandom.com/wiki/Shuro_Chi',
    'https://www.destinypedia.com/Morgeth,_the_Spirekeeper',
    'https://www.shacknews.com/article/108992/keep-out-destiny-2-last-wish-raid-challenge',
    'https://www.destinypedia.com/Riven_of_a_Thousand_Voices',
    'https://www.youtube.com/watch?v=415SSkgsIz8',
    'https://www.light.gg/db/items/298334059/inherent-truth/',
    'https://www.destinypedia.com/File:Consecreated_Mind_game.jpg',
    'https://www.shacknews.com/article/114369/garden-of-salvation-raid-guide-destiny-2',
    'https://screenrant.com/destiny-2-consecrated-mind-boss-guide-garden-salvation/',
    'https://www.destinypedia.com/Sanctified_Mind,_Sol_Inherent',
    'https://www.shacknews.com/article/121651/deep-stone-crypt-raid-guide-destiny-2',
    'https://www.destinypedia.com/Deep_Stone_Crypt_%28raid%29',
    'https://www.youtube.com/watch?v=VHi7Yj2lVCQ',
    'https://www.destinypedia.com/Atraks-1,_Fallen_Exo',
    'https://www.youtube.com/watch?v=5eSKA6SOzI4',
    'https://www.shacknews.com/article/131325/of-all-trades-challenge-destiny-2',
    'https://www.destinypedia.com/Taniks,_the_Scarred',
    'https://www.shacknews.com/article/124508/vault-of-glass-raid-guide-destiny-2',
    'https://www.light.gg/db/items/3953403255/share-a-glass/',
    'https://gamerant.com/destiny-2-beat-confluxes-encounter-vault-of-glass/',
    'https://www.destinypedia.com/The_Templar',
    'https://static.wikia.nocookie.net/destinypedia/images/9/9c/The_Gorgons_%28Grimoire_Card%29.jpg/revision/latest?cb=20150514213727',
    'https://www.thegamer.com/destiny-2-vault-of-glass-challenges-guide/',
    'https://www.destinypedia.com/Atheon,_Time%27s_Conflux',
    'https://www.shacknews.com/article/129163/vow-of-the-disciple-raid-guide-destiny-2',
    'https://www.youtube.com/watch?v=5hNytD8S-gs',
    'https://www.destinypedia.com/The_Caretaker',
    'https://www.gamesradar.com/destiny-2-defenses-down-exhibition-challenge/',
    'https://villains.fandom.com/wiki/Rhulk',
    'https://www.pinterest.com/pin/234116880623758789/',
    'https://www.destinypedia.com/Portico#/media/File:Portico_D2.jpg',
    'https://www.destinypedia.com/Basilica#/media/File:Basilica,_Dreadnaught,_Rings_of_Saturn_0.png',
    'https://destiny.wiki.gallery/images/thumb/5/52/Grimoire_Warpriest.jpg/300px-Grimoire_Warpriest.jpg',
    'https://www.shacknews.com/article/132165/gaze-amaze-challenge-destiny-2',
    'https://gamerant.com/destiny-2-kings-fall-daughters-of-oryx-guide/',
    'https://www.shacknews.com/article/132204/hands-off-challenge-destiny-2',
    'https://www.light.gg/db/legend/498211331/badges/1968454484/raid-root-of-nightmares/',
    'https://gamerant.com/destiny-2-how-to-complete-illuminated-torment-challenge-guide/',
    'https://gamerant.com/destiny-2-complete-crossfire-challenge-guide/',
    'https://gamerant.com/destiny-2-root-of-nightmares-macrocosm-encounter-guide-explicator-of-planets/',
    'https://www.destinypedia.com/Nezarec,_Final_God_of_Pain',
    'https://www.blueberries.gg/wp-content/uploads/2023/09/Crotas-End-raid-key-art-Destiny-2.jpg',
    'https://www.blueberries.gg/wp-content/uploads/2023/09/Abyss-Crotas-End-raid-Destiny-2.jpg',
    'https://www.shacknews.com/article/137253/precarious-balance-destiny-2',
    'https://www.shacknews.com/article/137341/equal-vessels-destiny-2',
    'https://destiny.fandom.com/wiki/Crota',
    'https://www.artstation.com/artwork/04yJew',
    'https://www.youtube.com/watch?v=VvNEwfyJpEE',
    'https://www.destinypedia.com/Herald_of_Finality',
    'https://screenrant.com/destiny-2-complete-every-salvations-edge-challenge/',
    'https://www.destinypedia.com/Verity',
    'https://www.shacknews.com/article/140572/the-witness-solo-destiny-2',
    'https://www.artstation.com/artwork/RKWvPO',
    'https://www.destinypedia.com/Epoptes,_Lord_of_Quanta',
    'https://www.destinypedia.com/Agraios,_Inherent',
    'https://www.destinypedia.com/Iatros,_Inward-Turned',
    'https://www.destinypedia.com/Koregos,_the_Worldline',
    'https://www.youtube.com/watch?v=u7T-VE7_bF0',
    'https://www.youtube.com/watch?v=OBw5xBigRko',
    'https://www.destinypedia.com/The_Shattered_Throne',
    'https://www.destinypedia.com/Vorgeth,_the_Boundless_Hunger',
    'https://www.pcgamer.com/destiny-2-pit-of-heresy-guide-dungeon-walkthrough/',
    'https://www.destinypedia.com/Necropolis',
    'https://www.destinypedia.com/Harrowing_Pariah',
    'https://www.shacknews.com/article/114869/pit-of-heresy-guide-destiny-2',
    'https://www.destinypedia.com/Zulmak,_Instrument_of_Torment',
    'https://www.shacknews.com/article/118838/prophecy-dungeon-guide-destiny-2',
    'https://www.destinypedia.com/Phalanx_Echo',
    'https://www.shacknews.com/article/118838/prophecy-dungeon-guide-destiny-2',
    'https://www.destinypedia.com/Prophecy',
    'https://www.blueberries.gg/weapons/grasp-of-avarice-loot/',
    'https://www.shacknews.com/article/128745/grasp-of-avarice-loot-table-destiny-2',
    'https://primagames.com/gaming/destiny-2-grasp-of-avarice-guide',
    'https://www.light.gg/db/legend/triumphs/3718971745/grasp-of-avarice-solo-flawless/',
    'https://techraptor.net/gaming/guides/destiny-2-grasp-of-avarice-dungeon-walkthrough-guide',
    'https://www.shacknews.com/article/128012/grasp-of-avarice-dungeon-guide-destiny-2',
    'https://www.destinypedia.com/Nightmare_of_Gahlran,_Sorrow_Bearer',
    'https://www.destinypedia.com/Duality_(dungeon)#/media/File:Dualitydun.jpg',
    'https://www.youtube.com/watch?v=TJrPiwXYpH0',
    'https://www.destinypedia.com/Nightmare_of_Caiatl,_Princess-Imperial',
    'https://www.destinypedia.com/Spire_of_the_Watcher',
    'https://www.dualshockers.com/destiny-2-spire-of-the-watcher-dungeon-guide/',
    'https://www.sportskeeda.com/esports/destiny-2-spire-watcher-guide-persys-primordial-ruin-boss-descend-encounter',
    'https://www.destinypedia.com/Akelous,_the_Siren%27s_Current',
    'https://www.destinypedia.com/File:PersysInfobox.jpg',
    'https://gamingcy.com/blog/ghosts-of-the-deep-loot-guide',
    'https://gamerant.com/destiny-2-ghosts-of-the-deep-dungeon-guide/',
    'https://www.fanbyte.com/destiny-2/guides/destiny-2-ghosts-of-the-deep-dungeon-guide-ecthar-encounter',
    'https://www.destinypedia.com/Ecthar,_Sword_of_Oryx',
    'https://www.destinypedia.com/%C5%A0immumah_ur-Nokru',
    'https://www.shacknews.com/article/137967/destiny-2-start-warlords-ruin',
    'https://primagames.com/gaming/how-to-get-out-of-the-jail-in-destiny-2-warlords-ruin',
    'https://www.destinypedia.com/Locus_of_Wailing_Grief#/media/File:LocusOfWG.jpg',
    'https://www.thegamer.com/destiny-2-warlords-ruin-dungeon-encounters-hidden-chests-guide/',
    'https://www.destinypedia.com/Hefnd%27s_Vengeance,_Blighted_Chimaera',
    'https://www.destinypedia.com/Vesper%27s_Host',
    'https://www.youtube.com/watch?v=-TXFFjtoeR4',
    'https://www.pcgamesn.com/destiny-2/vespers-host',
    'https://www.novarcan.com/jeux/destiny-2/donjons/hote-vesper/infiltration-et-l-enigme-des-reserves-de-puissance/',
    'https://gamerant.com/destiny-2-vespers-host-how-to-defeat-raneiks-unified-dungeon-guide/',
    'https://www.destinypedia.com/The_Corrupted_Puppeteer',
    'https://www.fanbyte.com/destiny-2/guides/destiny-2-grasp-of-avarice-dungeon-guide-encounter',
    'https://www.polygon.com/destiny-2-guide-walkthrough/521312/sundered-doctrine-dungeon-guide-walkthrough-encounter-symbols/',
    'https://dotesports.com/destiny/news/sundered-doctrine-first-encounter-guide-destiny-2-riddle',
    'https://www.destinypedia.com/Zoetic_Lockset',
    'https://dotesports.com/destiny/news/how-to-defeat-kerrev-the-erased-and-beat-the-third-encounter-in-sundered-doctrine-in-destiny-2',
    'https://gamerant.com/destiny-2-equilibrium-dungeon-guide-all-encounters-harvester-harrow-sere/',
    'https://thegamepost.com/destiny-2-equilibrium-dungeon-guide/',
    'https://www.destinypedia.com/Dredgen_Sere',
    'https://www.destinypedia.com/Harrow,_Dredgen-Apprentice'
  ];
}
